### ISSUE TITLE
Module Conflict with Monaco Macro Editor

### ISSUE THREAD

**Issue by HavocsCall** [krbz999/effectmacro#8] opened 2022-07-20 17:38 UTC
When using Monaco module editor, the macro edit window is just blank. This happens with all other modules deactivated as well.

**Comment by krbz999** [comment] 2022-07-20 19:18
I can make a quick fix for this for the next update, however the problem is on Monaco's end and the way it inserts its own editor by looking for irrelevant elements on the macro editor UI. I would like to suggest you make an issue on their page.

**Comment by HavocsCall** [comment] 2022-07-20 20:37
Will do

**Comment by krbz999** [comment] 2022-07-31 21:33
This has been fixed (on my end) in the pending v10 release, and shouldn't change anything about how the editor looks for anyone not using Monaco.

As for an issue logged to them, they can append their editor before the editor that they hide (which is always present), rather than after the 'type' dropdown (which in this case was not present).

Thank you for logging the issue!

**Closed by krbz999** 2022-07-31 21:33 UTC
Labels: bug
